### ISSUE TITLE
Add missing tag v2.02

### ISSUE THREAD

**Issue by dkinzer** [twilson63/s3fs-recipe#23]
@twilson63 would it be possible for you to add a v2.0.2 tag at 40f6e3c869e07277b0d93b4a07eaa0ff98322055 ?

There's a backwards compatible change at v2.0.3 but I can't reference v2.0.2 on my bekshelf because there's not tag for it at this point.

Thanks!

**Comment by dkinzer** [comment]
I stopped using chef at work so  no longer need this.  BTW request above is possible .. you need to add a tag to the an older commit

`git tag -a v1.2 9fceb02 -m "Message here"`

and then push to repo:

 `git push --tags`

**Comment by twilson63** [comment]
I will add it, I stop using chef a long while ago, I try to keep up this
lib, but hard to find time these days, thanks for the help!

Tom


On Tue, Sep 1, 2015 at 9:00 AM, David Kinzer <notifications@github.com>
wrote:

> I stopped using chef at work so no longer need this. BTW request above is
> possible .. you need to add a tag to the an older commit
>
> git tag -a v1.2 9fceb02 -m "Message here"
>
> and then push to repo:
>
> git push --tags
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twilson63/s3fs-recipe/issues/23#issuecomment-136709644>
> .
>



-- 
Tom Wilson
Jack Russell Software, A Tabula Rasa Healthcare Division
494 Wando Park Blvd
Mount Pleasant, SC  29464
Phone: 843-606-6484
Mobile: 843-469-5856
Email: tom@jackhq.com
Web: http://www.jackhq.com
Calendar:
http://www.google.com/calendar/embed?src=tom%40jackrussellsoftware.com&ctz=America/New_York
<http://www.jackhq.com/calendar>

This e-mail may contain information that is confidential, privileged or
otherwise protected from disclosure by the Health Insurance Portability and
Accountability Act (HIPAA) and other state and federal laws.  This
information is intended only for the individual names above.  Any review,
use disclosure or dissemination of this material is strictly prohibited.
If you receive this information in error, please notify CareKinesis
immediately at 888-974-2763 and delete the original at once.
